### ISSUE TITLE
Oh Snap: Could not connect to host: x.x.x.x  , port:22

### ISSUE THREAD

**Issue by klevinkona** [banago/PHPloy#372]
Debian 10 version OS
php 7.3 
Tested ssh connection directly from terminal and works ok. when i run deploy i have the following error "Oh Snap: Could not connect to host: x.x.x.x  , port:22"

Running "phploy --debug" i see the following:

PHP Fatal error:  Uncaught Error: Call to undefined function League\CLImate\Argument\mb_strtolower() in phar:///usr/local/bin/phploy/vendor/league/climate/src/Argument/Filter.php:181
Stack trace:
#0 phar:///usr/local/bin/phploy/vendor/league/climate/src/Argument/Filter.php(165): League\CLImate\Argument\Filter->prefixCompareString(Object(League\CLImate\Argument\Argument))
#1 [internal function]: League\CLImate\Argument\Filter->compareByPrefix(Object(League\CLImate\Argument\Argument), Object(League\CLImate\Argument\Argument))
#2 phar:///usr/local/bin/phploy/vendor/league/climate/src/Argument/Filter.php(87): usort(Array, Array)
#3 phar:///usr/local/bin/phploy/vendor/league/climate/src/Argument/Filter.php(46): League\CLImate\Argument\Filter->filterArguments(Array)
#4 phar:///usr/local/bin/phploy/vendor/league/climate/src/Argument/Parser.php(269): League\CLImate\Argument\Filter->withPrefix()
#5 phar:///usr/local/bin/phploy/vendor/league/climate/src/Argument/Parser.php(200): League\CLImate\Argument\Parser->findPrefixedArgument('--de in phar:///usr/local/bin/phploy/vendor/league/climate/src/Argument/Filter.php on line 181

**Comment by klevinkona** [comment]
Solved, missing the scheme
    scheme = sftp
