### ISSUE TITLE
Fata error Launching phploy with php 8.1

### ISSUE THREAD

**Issue by olivierbussier** [banago/PHPloy#402]
phploy version : v4.9.1

My config file:
```
[ovhpreprod]
scheme = sftp

```
The result i got:

```shell
-------------------------------------------------
|                     PHPloy                    |
-------------------------------------------------
LIST mode: No remote files will be modified.
PHP Fatal error:  Uncaught Error: Class "League\Flysystem\Sftp\SftpAdapter" not found in /var/www/html/back/vendor/banago/phploy/src/Connection.php:119
Stack trace:
#0 /var/www/html/back/vendor/banago/phploy/src/Connection.php(37): Banago\PHPloy\Connection->connectToSftp()
#1 /var/www/html/back/vendor/banago/phploy/src/PHPloy.php(737): Banago\PHPloy\Connection->__construct()
#2 /var/www/html/back/vendor/banago/phploy/src/PHPloy.php(791): Banago\PHPloy\PHPloy->connect()
#3 /var/www/html/back/vendor/banago/phploy/src/PHPloy.php(331): Banago\PHPloy\PHPloy->deploy()
#4 /var/www/html/back/vendor/banago/phploy/bin/phploy(14): Banago\PHPloy\PHPloy->__construct()
#5 /var/www/html/back/vendor/bin/phploy(119): include('...')
#6 {main}
  thrown in /var/www/html/back/vendor/banago/phploy/src/Connection.php on line 119
olivier@devweb:/var/www/html/back$ 
```

**Comment by isuke01** [comment]
I think that's related to #399
Idk when it is going to be solved :|

**Comment by banago** [comment]
@olivierbussier sorry for missing for this long. Please grab the new version. This has been fixed.

**Comment by olivierbussier** [comment]
Thanks for this app and your work

**Comment by banago** [comment]
Thank you too @olivierbussier for using PHP and for the kind words.
