### ISSUE TITLE
SftpAdapter not found

### ISSUE THREAD

**Issue by a-mian-lateral** [banago/PHPloy#407]
Hi, I have been using Phploy for a couple of years without any problems, but lately I am having some problems.

```
PHP Fatal error:  Uncaught Error: Class "League\Flysystem\Sftp\SftpAdapter" not found in /Users/***/vendor/banago/phploy/src/Connection.php:119
Stack trace:
#0 /Users/***/vendor/banago/phploy/src/Connection.php(37): Banago\PHPloy\Connection->connectToSftp(Array)
#1 /Users/***/vendor/banago/phploy/src/PHPloy.php(737): Banago\PHPloy\Connection->__construct(Array)
#2 /Users/***/vendor/banago/phploy/src/PHPloy.php(791): Banago\PHPloy\PHPloy->connect(Array)
#3 /Users/***/vendor/banago/phploy/src/PHPloy.php(331): Banago\PHPloy\PHPloy->deploy()
#4 /Users/***/vendor/banago/phploy/bin/phploy(14): Banago\PHPloy\PHPloy->__construct()
#5 /Users/***/vendor/bin/phploy(119): include('/Users/a-mian-l...')
#6 {main}
  thrown in /Users/***/vendor/banago/phploy/src/Connection.php on line 119
```

I'm using PHP 8.2.21 and Composer 2.7.7

If you need more details please let me know, this is the first time I am having problems with this library so I am not sure where to investigate.

**Comment by banago** [comment]
I'll get to this soon. Thank you for using PHPloy.

**Comment by banago** [comment]
@a-mian-lateral please grab the latest version.
